# Generated by Django 3.1.4 on 2021-01-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemscategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='itemsize',
            table=None,
        ),
    ]
