# Generated by Django 3.1.4 on 2021-01-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'CASH_ON_DELIVERY'), (2, 'CARD'), (3, 'Other')], null=True),
        ),
    ]
