# Generated by Django 3.1.4 on 2021-01-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_number',
            new_name='order',
        ),
    ]
