# Generated by Django 3.1.4 on 2021-01-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_number',
        ),
        migrations.AddField(
            model_name='orders',
            name='is_checkedout',
            field=models.BooleanField(default=False),
        ),
    ]
